cc_test(
    name = "tests",
    srcs = ["FractionTest.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/class/fraction:fraction",
        "//src/class/matrix:matrix",
        "//src/class/list:list",
    ]
)
