## src/class/BUILD

cc_library(
    name = "class",
    srcs = ["person.cpp","student.cpp","professor.cpp","studentEntered.cpp","studentFirstSession.cpp","studentSecondSession.cpp", "tree.cpp", "forestTree.cpp", "fruitTree.cpp", "caseTree.cpp"],
    hdrs = ["person.hpp","student.hpp","professor.hpp","studentEntered.hpp","studentFirstSession.hpp","studentSecondSession.hpp", "tree.hpp", "forestTree.hpp", "fruitTree.hpp","caseTree.hpp"],
    visibility = ["//visibility:public"],
)
